#  --------  DEPLOYMENT   --------  #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja
spec:
  selector:
    matchLabels:
      app: aplikacja
  replicas: {{ .Values.replicasNumber }}
  template: # template for the pods
    metadata:
      labels:
        app: aplikacja
    spec:
      containers:
      - name: aplikacja
        image: {{ .Values.containerImage }}
---
#  --------  SERVICE   --------  #

apiVersion: v1
kind: Service
metadata:
  name: aplikacja-service

spec:

  selector:
    app: aplikacja
    
  ports:
    - name: http
      port: 80
      nodePort: 30001

  type: NodePort        

